apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - image: svishnevskii/fpm:v5
          name: app
          volumeMounts:
          - name: data
            mountPath: /var/www/html
        #   # Important! After this container has started, the PHP files
        #   # in our Docker image aren't in the shared volume. We need to 
        #   # get them into the shared volume. If we tried to write directly
        #   # to this volume from our Docker image the files wouldn't appear
        #   # in the nginx container.
        #   #
        #   # So, after the container has started, copy the PHP files from this
        #   # container's local filesystem (/app -- added via the Docker image) 
        #   # to the shared volume, which is mounted at /var/www/html.
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "ln -s /app/hello.php /var/www/html/"]
        - image: svishnevskii/nginx:v1
          name: nginx
          ports:
          - containerPort: 80
          volumeMounts:
          # - name: config
          #   mountPath: /etc/nginx/conf.d/
          - name: data
            mountPath: /var/www/html
      volumes:
      # - name: config
      #   configMap:
      #     name: my-configmap
      - name: data
        persistentVolumeClaim:
          claimName: my-persistent